// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc2JqFjJas_Httz-G--AMaBub9d9h5ET0',
    appId: '1:576317568080:web:0d82760e77b62b06050d55',
    messagingSenderId: '576317568080',
    projectId: 'beeginner-4a1ad',
    authDomain: 'beeginner-4a1ad.firebaseapp.com',
    storageBucket: 'beeginner-4a1ad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSLI5JeQJMsIEhgJkzs7zptYWDP0pPboc',
    appId: '1:576317568080:android:a7ed2c2a31ccf939050d55',
    messagingSenderId: '576317568080',
    projectId: 'beeginner-4a1ad',
    storageBucket: 'beeginner-4a1ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuKN5RgmvGK_MVv5tBH5j_wAt0nOekNv4',
    appId: '1:576317568080:ios:62e236c747913afb050d55',
    messagingSenderId: '576317568080',
    projectId: 'beeginner-4a1ad',
    storageBucket: 'beeginner-4a1ad.appspot.com',
    iosBundleId: 'com.example.beeginner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuKN5RgmvGK_MVv5tBH5j_wAt0nOekNv4',
    appId: '1:576317568080:ios:3be62d62a571f542050d55',
    messagingSenderId: '576317568080',
    projectId: 'beeginner-4a1ad',
    storageBucket: 'beeginner-4a1ad.appspot.com',
    iosBundleId: 'com.example.beeginner.RunnerTests',
  );
}
